// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VeaFooter: typeof import('./../src/container/components/VeaFooter/VeaFooter.vue')['default']
    VeaHeader: typeof import('./../src/container/components/VeaHeader/VeaHeader.vue')['default']
    VeaIcon: typeof import('./../src/container/components/VeaIcon/VeaIcon.vue')['default']
    VeaLogo: typeof import('./../src/container/components/VeaLogo/VeaLogo.vue')['default']
    VeaMain: typeof import('./../src/container/components/VeaMain/VeaMain.vue')['default']
    VeaMenu: typeof import('./../src/container/components/VeaMenu/VeaMenu.vue')['default']
    VeaMenuItem: typeof import('./../src/container/components/VeaSider/components/VeaMenuItem.vue')['default']
    VeaSider: typeof import('./../src/container/components/VeaSider/VeaSider.vue')['default']
    VeaSubMenu: typeof import('./../src/container/components/VeaSider/components/VeaSubMenu.vue')['default']
  }
}
